#!/usr/bin/env bash

rm -rf $BASEDIR"/Test_3"
mkdir $BASEDIR"/Test_3"
echo
echo "Generating data for Test 3 folder with 5,000 items of each class with mutation rate 0.6"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.6 1 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.6 2 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_3/file1.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.6 3 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.6 4 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_3/file2.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.6 5 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.6 6 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_3/file3.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.6 7 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.6 8 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_3/file4.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.6 0 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.6 0 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_3/file5.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.6 20 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.6 20 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_3/file6.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
echo "Dataset of Test 3 Generated"
echo
echo