#!/usr/bin/env bash

rm -rf $BASEDIR"/Test_1"
mkdir $BASEDIR"/Test_1"
echo
echo "Generating data for Test 1 folder with 5,000 items of each class with mutation rate 0.2."
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.2 1 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.2 2 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_1/file1.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.2 3 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.2 4 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_1/file2.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.2 5 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.2 6 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_1/file3.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.2 7 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.2 8 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_1/file4.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.2 0 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.2 0 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_1/file5.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.2 20 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.2 20 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_1/file6.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
echo "Data set of Test 1 Generated"
echo
echo
