#!/usr/bin/env bash

rm -rf $BASEDIR"/Test_2"
mkdir $BASEDIR"/Test_2"
echo
echo "Generating data for Test 2 folder with 5,000 items of each class with mutation rate 0.4"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.4 1 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.4 2 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_2/file1.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.4 3 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.4 4 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_2/file2.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.4 5 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.4 6 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_2/file3.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.4 7 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.4 8 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_2/file4.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.4 0 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.4 0 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_2/file5.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.4 20 $BASEDIR"/out1.txt"
python $BASEDIR"/sticky_snippet_generator.py" 2500 0.4 20 $BASEDIR"/out2.txt"
cat $BASEDIR"/out1.txt" $BASEDIR"/out2.txt" > $BASEDIR"/Test_2/file6.txt"
rm -rf $BASEDIR"/out1.txt"
rm -rf $BASEDIR"/out2.txt"
echo "Dataset of Test 2 Generated"
echo
echo

